### ISSUE TITLE
Allow the user to enter their username or phone number, instead of chatid

### ISSUE THREAD

**Issue by xow** [mchurchward/moodle-message_output_telegram#2]
This could be done by requesting the chat id for a username or phonenumber from the telegram api

**Comment by mchurchward** [comment]
Can you point me to the documentation for this API?

**Comment by xow** [comment]
We could ask the user to share their contact with the bot, then call getUpdates, then search the result for their user

**Comment by mchurchward** [comment]
[Version 3.2.4](https://moodle.org/plugins/pluginversion.php?id=14090) adds a better user experience. The user just needs to click a link to open the bot and press "Start". Moodle will look for their session id to match the account to the Telegram user, and then grab the chatid from there.
