### ISSUE TITLE
Curl class not included

### ISSUE THREAD

**Issue by xow** [mchurchward/moodle-message_output_telegram#3]
Messages do not work at all. I guess the notifications coincidentally already include lib/filelib.php

Just need to add.
```
require_once($CFG->dirroot.'/lib/filelib.php')
```

**Comment by mchurchward** [comment]
I cannot replicate this problem. Can you post the steps that show this issue?

**Comment by xow** [comment]
I'm unable to reproduce today so I'll close this.

Here was the error in case it ever comes up again

```
PHP Fatal error:  Class 'curl' not found in /home/vagrant/moodles/stable_master_mysql/moodle/message/output/telegram/message_output_telegram.php on line 68, referer: http://john-mac.per.in.moodle.com:4325/stable_master_mysql/message/index.php?contactsfirst=1
```
